apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-tls
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: argocd
spec:
  secretName: argocd-tls
  dnsNames:
    - "argocd.paoloose.site"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
