apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yml
  - certificate.yml

helmCharts:
  - name: argo-cd
    version: 7.8.8
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    valuesFile: values.yml
    namespace: argocd
