apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yml
  - issuer.yml

helmCharts:
  - name: cert-manager
    version: 1.17.1
    releaseName: cert-manager
    includeCRDs: true
    repo: https://charts.jetstack.io
    valuesFile: values.yml
    namespace: cert-manager
